---
name: SBT
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  firebase_database: ^3.1.6
  firebase_core: ^0.4.5
  cloud_firestore: any
  firebase_storage: ^3.1.6
  provider: ^4.3.1
  carousel_pro: ^1.0.0
  flutter_spinkit: ^4.1.2
  url_launcher: ^5.5.2
  geolocator: ^5.1.5
  image_picker: ^0.6.7+7
  image_cropper: ^1.3.1
  flutter_speed_dial: ^1.2.5
  flutter_open_whatsapp: ^0.1.2
  razorpay_flutter: ^1.2.2
  fluttertoast: ^7.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - images/
  fonts:
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico/Pacifico-Regular.ttf
  - family: Lato
    fonts:
    - asset: fonts/Lato/Lato-Bold.ttf
    - weight: 600
    - asset: fonts/Lato/Lato-Light.ttf
    - weight: 100
    - asset: fonts/Lato/Lato-Black.ttf
    - weight: 300
